<a href="https://colab.research.google.com/github/dymiyata/wva-ml-ai-2-2026-2027/blob/main/demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/dymiyata/wva-ml-ai-2-2026-2027/refs/heads/main/classification_data/classification_class.csv")

In [ ]:
df.head()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,target
0,-1.030931,1.391626,0.547274,0.928932,-1.738880,1.250002,1.332551,1.578256,2.124722,-0.318434,0
1,-2.766254,1.247870,-0.303691,1.083145,0.710836,1.968202,-1.794192,2.346422,1.700778,-0.001190,1
2,-0.558987,0.299849,1.527071,0.360442,-1.360209,1.100793,-0.755951,1.331933,2.041105,-0.824404,0
3,-1.350289,-2.046078,-0.614264,0.126459,-0.783923,5.895026,-0.915477,-3.184768,-0.399260,-3.920960,0
4,-0.275754,-0.728495,0.027727,-0.660834,-1.928161,3.544945,1.446944,-1.111662,0.313766,-2.376528,0


### Scikit-learn

A library for datascience/basic machine learning.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
X = df.drop("target", axis=1)
y = df["target"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=2026
)

In [ ]:
model_log = LogisticRegression()

In [ ]:
model_log.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred_train = model_log.predict(X_train)
y_pred_test = model_log.predict(X_test)

In [ ]:
print(confusion_matrix(y_train, y_pred_train))
print(accuracy_score(y_train, y_pred_train))

[[305  82]
 [ 61 352]]
0.82125


In [ ]:
print(confusion_matrix(y_test, y_pred_test))
print(accuracy_score(y_test, y_pred_test))

[[92 19]
 [ 9 80]]
0.86


### Tensor Flow

Library for deep stuff.

In [ ]:
from tensorflow import keras

In [ ]:
model_neural = keras.Sequential([
    keras.layers.Input(shape=(10,)),
    keras.layers.Dense(200, activation="relu"),
    keras.layers.Dense(100, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")
])

In [ ]:
model_neural.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [ ]:
model_neural.fit(X_train, y_train, epochs=16)

Epoch 1/16
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7950 - loss: 0.4454
Epoch 2/16
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8450 - loss: 0.3152
Epoch 3/16
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8888 - loss: 0.2689
Epoch 4/16
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9075 - loss: 0.2384
Epoch 5/16
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9162 - loss: 0.2171 
Epoch 6/16
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9175 - loss: 0.2008 
Epoch 7/16
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9275 - loss: 0.1911
Epoch 8/16
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9300 - loss: 0.1807 
Epoch 9/16
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9413 - loss: 0.1734
Epoch 10/16
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9388 - loss: 0.1600
Epoch 11/16
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9463 - loss: 0.1533
Epoch 12/16
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9488 

In [ ]:
y_pred_train_n = (model_neural.predict(X_train) > 0.5).astype(int)
y_pred_test_n = (model_neural.predict(X_test)>0.5).astype(int)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


In [ ]:
print(confusion_matrix(y_train, y_pred_train_n))
print(accuracy_score(y_train, y_pred_train_n))


print(confusion_matrix(y_test, y_pred_test_n))
print(accuracy_score(y_test, y_pred_test_n))

[[374  13]
 [ 18 395]]
0.96125
[[101  10]
 [  6  83]]
0.92
